### ISSUE TITLE
Add warning when all labels are False

### ISSUE THREAD

**Issue by rvandewater** [justin13601/ACES#142]
Because of code changes, we could end up with a task df that has all labels as False (this happens when defining `DEATH `instead of `MEDS_DEATH `with newer MEDS extracted datasets for example https://github.com/mmcdermott/MEDS_transforms/issues/209). Perhaps you could warn users of this?

**Comment by justin13601** [comment]
Thanks for the headsup - I'll add a warning for cases where the labels are all False.

Maybe it is also worth adding one for where the labels are all True? I'd imagine something probably went wrong with the cohort if your task all has that one label, so adding a warning doesn't hurt.

Since we're only dealing with binary labels currently, we can also return a count of the numbers of positive/negative samples, if it makes it easier to use.

**Comment by rvandewater** [comment]
Sounds good!
